### ISSUE TITLE
utf-8 special charatecters  problem with some email clients sending mail with inline images (base64 encoded)

### ISSUE THREAD

**Issue by beverfood** [PHPMailer/PHPMailer#279] opened 2014-09-22 15:46 UTC
Hi,
First of all I would like to thank you for your great work.
I have a problem with some email clients when sending email in html utf-8 that contain special characters and i insert one or more inline images (base64 encoded).
It works good with Thunderbird, Gmail, Opera Mail but in Windows Mail and MS Outlook for example the text: "èé@àààùè" became "Ã¨Ã©@Ã Ã Ã Ã¹Ã¨". If I don't add inline images work well with all the client i tested.

**Comment by Synchro** [comment] 2015-03-25 20:56
Please can you check out the master branch which has some changes relating to this and give it a try - I've tried various things but I can't make it go wrong as you describe. See also #377

**Comment by Synchro** [comment] 2015-09-02 06:59
Closing due to no feedback.

**Closed by Synchro** 2015-09-02 06:59 UTC

**Comment by ortodata** [comment] 2017-04-14 23:36
$mail->CharSet = "UTF-8";

**Comment by david20240** [comment] 2019-02-18 14:29
Hi Synchro,
I work as a French City Hall webmaster and we have a trouble receiving emails with french accents.
I went everywhere on your Github phpmailer and I have done what you explained like:
-$mail->CharSet = 'utf-8';
-All the html pages are in utf8
mbstring is on
And nothing is OK the accents are not OK and when there is accents in the body message, the message body is empty ;-)
I use phpmailer 5.2.20 and I cannot change to 6.0.6 as I will have to modify the whole things
`<?php
session_start();

include("php/abcdefghikjl/PHPMailerAutoload.php");

$to = 'commune@domain.fr';

if(isset($_POST['emailSent'])) {

	$subject = utf8_decode($_POST[‘subject’]);

	if (strtolower($_POST["captcha"]) == strtolower($_SESSION['captcha']['code'])) {

		$name = $_POST['name'];
		$email = $_POST['email'];
        $message = $_POST['message'];
        $message = utf8_decode($message);

		// Step 3 - Configure the fields list that you want to receive on the email.
		$fields = array(
			0 => array(
				'text' => 'Nom',
				'val' => $_POST['name']
			),
			1 => array(
				'text' => 'Adresse Email',
				'val' => $_POST['email']
			),
			2 => array(
				'text' => 'Message',
				'val' => $_POST['message']
			),
            3 => array(
		        'text' => 'Objet de ce Message',
		        'val' => $_POST['select']
	        ),
			4 => array(
				'text' => '-Raisons de votre Demande',
				'val' => implode($_POST['checkboxes'], ", ")
			),
			5 => array(
				'text' => '-Qui souhaitez-vous Rencontrer',
				'val' => $_POST['radios']
			)
		);

		$message = "";

		foreach($fields as $field) {
			$message .= $field['text'].":  " . htmlspecialchars($field['val'], ENT_QUOTES) . "<br>\n";
		}

		$mail = new PHPMailer;
        $mail->isHTML(true);
        $mail->CharSet = 'utf-8';

		//$mail->IsSMTP();                                      // Set mailer to use SMTP
		//$mail->SMTPDebug = 0;                                 // Debug Mode

		$mail->Host = 'mail.domain.fr';				  // Specify main and backup server
		$mail->SMTPAuth = true;                             // Enable SMTP authentication
		$mail->Username = 'noreply@domain.fr';               // SMTP username
		$mail->Password = 'secretpassword';                         // SMTP password
		$mail->SMTPSecure = 'tls';                          // Enable encryption, 'ssl' also accepted
		$mail->Port = 587;   								  // TCP port to connect to

		$mail->From = $email;
		$mail->FromName = $_POST['name'];
		$mail->AddAddress($to);
		$mail->AddReplyTo($email, $name);

		$mail->IsHTML(true);
     

		$mail->Subject = $subject;
		$mail->Body    = $message;
        

		

		if($mail->Send()) {
			$arrResult = array('response'=> 'success');
		} else {
			$arrResult = array('response'=> 'error', 'error'=> $mail->ErrorInfo);
		}

	} else {

		$arrResult['response'] = 'captchaError';

	}

}
?>`
And my message input is:
`<div class="row">
									<div class="form-group">
										<div class="col-md-12">
											<label>Message</label>
											<textarea maxlength="1000" data-msg-required="Merci de saisir votre Message" rows="5" class="form-control" name="message" id="message" required></textarea>
										</div>
									</div>
								</div>

-----
Please, can help do solving this accent troubles as users are complaining to the City Hall and I do not know what to answer
I really thank you if you may help
David`

**Comment by Synchro** [comment] 2019-02-19 11:10
Bonjour David,

The problem is that you are doing this:

    $subject = utf8_decode($_POST[‘subject’]);
    $message = utf8_decode($message);

[`utf8_decode`](https://secure.php.net/manual/fr/function.utf8-decode.php) converts valid UTF-8 text into the ISO-8859-1 charset, which is absolutely **not** what you want! You want everything in UTF-8, all the time - all your pages, scripts, editors, everything. If your'e doing that then it should "just work" by setting `CharSet = 'utf-8'`.

I also note in that `$_POST[‘subject’]` line above it's using the wrong kind of quotes.

**Comment by david20240** [comment] 2019-02-19 13:01
Bonjour Synchro,
I'll try this and I'll let you know
Thanks a lot for your time ;-) et MERCI ;-)
David

**Comment by david20240** [comment] 2019-02-19 14:23
Hi Again Synchro,
I am really sorry to inform you that the message is now empty:
--------------------
````
Nom: David Albertini
Adresse Email: david.albertini2@gmail.com
**Message:** 
Objet de ce Message: **Demenagement** 
-Raisons de votre Demande: Mutation Definitive, Mutation Temporaire, Retraite
-Qui souhaitez-vous Rencontrer: Antoine
``` 
`
As you may see, **Message is empty** and ### Demenagement is without accents like 
**Déménagement**
And I strictly done what you told me.
_Underneath do find the form_
`<?php
session_start();

include("php/@7PSBYyAFFDzzU64/PHPMailerAutoload.php"); 

$to = 'commune@domain.fr';

if(isset($_POST['emailSent'])) {

	$subject = $_POST['subject'];

	if (strtolower($_POST["captcha"]) == strtolower($_SESSION['captcha']['code'])) {

		$name = $_POST['name'];
		$email = $_POST['email'];
        $message = $_POST['message'];
        

		// Step 3 - Configure the fields list that you want to receive on the email.
		$fields = array(
			0 => array(
				'text' => 'Nom',
				'val' => $_POST['name']
			),
			1 => array(
				'text' => 'Adresse Email',
				'val' => $_POST['email']
			),
			2 => array(
				'text' => 'Message',
				'val' => $_POST['message']
			),
            3 => array(
		        'text' => 'Objet de ce Message',
		        'val' => $_POST['select']
	        ),
			4 => array(
				'text' => '-Raisons de votre Demande',
				'val' => implode($_POST['checkboxes'], ", ")
			),
			5 => array(
				'text' => '-Qui souhaitez-vous Rencontrer',
				'val' => $_POST['radios']
			)
		);

		$message = "";

		foreach($fields as $field) {
			$message .= $field['text'].":  " . htmlspecialchars($field['val'], ENT_QUOTES) . "<br>\n";
		}

		$mail = new PHPMailer;
        $mail->isHTML(true);
        $mail->CharSet = 'utf-8';

		//$mail->IsSMTP();                                      // Set mailer to use SMTP
		//$mail->SMTPDebug = 0;                                 // Debug Mode

		$mail->Host = 'mail.domain.fr';				  // Specify main and backup server
		$mail->SMTPAuth = true;                                        // Enable SMTP authentication
		$mail->Username = 'noreply@domain.fr';               // SMTP username
		$mail->Password = 'xxxxxxxxxxxxxxxxxx';                 // SMTP password
		$mail->SMTPSecure = 'tls';                                        // Enable encryption, 'ssl' also accepted
		$mail->Port = 587;   						  // TCP port to connect to

		$mail->From = $email;
		$mail->FromName = $_POST['name'];
		$mail->AddAddress($to);
		$mail->AddReplyTo($email, $name);

		$mail->IsHTML(true);

		      

		$mail->Subject = $subject;
		$mail->Body    = $message;
        

		

		if($mail->Send()) {
			$arrResult = array('response'=> 'success');
		} else {
			$arrResult = array('response'=> 'error', 'error'=> $mail->ErrorInfo);
		}

	} else {

		$arrResult['response'] = 'captchaError';

	}

}
?>`
Synchro, I am really sorry to bother you again with this kind of little troubles,
I may also give you all my credentials if you may take time to see what's going on
Thanks again for helping me MERCI
David

**Comment by Synchro** [comment] 2019-02-19 14:29
You need to be absolutely sure where the text is going astray, so test using fixed strings instead of your form, for example:

    $mail->Subject = 'Déménagement';

A separate problem is this:

    $mail->From = $email;

That is forgery and will result in your messages being spam-filtered or bounced. Put your own address in there and use the submitter's address as a reply-to address (which you're already doing).

**Comment by david20240** [comment] 2019-02-19 14:46
OK @Synchro I'll do what you answered me and I'll tell you ;-)
Merci beaucoup, il fait beau à Sallanches ??

**Comment by david20240** [comment] 2019-02-19 15:37
@Synchro 
**OK all is now fine for the body message in french with accents** except that the checkboxes and radios does not accept french accents ;-)
I really do not understand what's going on.
`<div class="row">
												<div class="col-md-12">
													<div class="checkbox-group">
														<label class="checkbox-inline">
															<input type="checkbox" name="checkboxes[]" type="checkbox" data-msg-required="Merci de choisir une option" id="inlineCheckbox1" value="Mutation Définitive">Mutation Définitive
														</label><br />
                                                        <label class="checkbox-inline">
															<input type="checkbox" name="checkboxes[]" type="checkbox" data-msg-required="Merci de choisir une option." id="inlineCheckbox2" value="Mutation Temporaire">Mutation Temporaire
														</label><br />
														<label class="checkbox-inline">
															<input type="checkbox" name="checkboxes[]" type="checkbox" data-msg-required="Merci de choisir une option." id="inlineCheckbox3" value="Retraite">Retraite
														</label><br />
														<label class="checkbox-inline">
															<input type="checkbox" name="checkboxes[]" type="checkbox" data-msg-required="Merci de choisir une option." id="inlineCheckbox4" value="Scolarité/Crèche">Scolarité/Crèche
														</label><br />
														<label class="checkbox-inline">
															<input type="checkbox" name="checkboxes[]" type="checkbox" data-msg-required="Merci de choisir une option." id="inlineCheckbox5" value="Autre Question">Autre Question
														</label><br />
													</div>
												</div>
											</div>
										</div>
										<div class="col-md-6">
											<div class="row">
												<div class="col-md-12">
													<label>Qui souhaitez-vous Rencontrer?</label>
												</div>
											</div>
											<div class="row">
												<div class="col-md-12">
													<div class="radio-group">
														<label class="radio-inline">
															<input type="radio" name="radios" data-msg-required="Merci de choisir une option." id="inlineRadio1" value="Mr Le Maire">RDV Mr Le Maire
														</label><br />
														<label class="radio-inline">
															<input type="radio" name="radios" data-msg-required="Merci de choisir une option." id="inlineRadio2" value="Antoine ">RDV 1er Adjoint
														</label><br />
														<label class="radio-inline">
															<input type="radio" name="radios" data-msg-required="Merci de choisir une option." id="inlineRadio3" value="Victor">RDV 2ème Adjoint
														</label><br />
														<label class="radio-inline">
															<input type="radio" name="radios" data-msg-required="Merci de choisir une option." id="inlineRadio4" value="Dominique ">RDV 3ème Adjoint
														</label><br />
														<label class="radio-inline">
															<input type="radio" name="radios" data-msg-required="Merci de choisir une option." id="inlineRadio5" value="Autre Rendez-vous">Autre Rendez-vous
														</label><br />
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>`
Thank you so much for helping me so far
David

**Comment by david20240** [comment] 2019-02-19 15:46
Hi @Synchro 
Thank you 👍 so much as It works for now and It was my fault ;-)
I had introduce in my Centos 7 specific php like 8859-1 and both iso-8859-1 and UTF-8 were doing the job ;-) ;-)
Thanks again for your help
David

**Comment by Synchro** [comment] 2019-02-19 16:08
Oui, il fait une belle journée 🏔☀️ - pas comme mon français! Je suis heureux vous avez résolu le problème!
