### ISSUE TITLE
The Latest PHPMailer v 5.2.14 some functions not support 'org' letters

### ISSUE THREAD

**Issue by beijingnj** [PHPMailer/PHPMailer#562] opened 2015-11-16 23:49 UTC
Why the $mail -> setForm; $mail -> addReplyTo; $mail -> addAddress and $mail - Body does not work when word with 'org'? No error message. But no can recieve email.

**Comment by Synchro** [comment] 2015-11-17 08:06
There is no such filtering. Please post your code to reproduce this.

**Comment by beijingnj** [comment] 2015-11-17 14:45
Here is my basic code:

<?php

include '../class.phpmailer.php';
include '../PHPMailerAutoload.php';
//Create a new PHPMailer instance
$mail = new PHPMailer;
// Set PHPMailer to use the sendmail transport
$mail->isSendmail();

$mail->setFrom('from@example.org');

$mail->addReplyTo('replyto@example.org');

$mail->addAddress('whoto1@example.org');
$mail->addAddress('whoto2@example.org');
$mail->addAddress('whoto3@example.org');

$mail->Subject = 'PHPMailer sendmail test';

$mail->Body = '$content';    //the content include - like 'go to website http://www.someschool.org'

if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo "Message sent!";
}

I have tested the function one by one. If I include the word '.org', no one receive email. I haven't tested like '.net' or '.gov'. but with '.com' it work fine.

Thank you in advance.

**Comment by robyrobrob** [comment] 2015-11-17 14:56
https://github.com/robyrobrob/phpsir/blob/master/register.php

This script uses PHPMailer+SMTP classes, and sends email to a .org TLD.

**Comment by Synchro** [comment] 2015-11-17 15:02
Because you're using sendmail, it's using your local mail server (and is not using the SMTP class), so you need to look in your mail server logs to see what's going on. You may find it useful to switch to `isSMTP()` and set `Host = ' localhost'` and `SMTPDebug = 2`, as then you will get more feedback on the message submission.

**Comment by beijingnj** [comment] 2015-11-19 14:42
Hi Synchro,

I have tried SMTP class. it still has the same issue. '.com' works. but not work for '.org'. Please see my code below.
<?php
include_once $cwd.'include/class.phpmailer.php';
include_once $cwd.'include/class.smtp.php';

include_once $cwd.'include/PHPMailerAutoload.php';

$mail = new PHPMailer();

//$mail->SMTPDebug = 2;  // debugging: 1 = errors and messages, 2 = messages only

$mail->isSMTP(); // enable SMTP
$mail->Host = 'smtp.mydomain.org';
$mail->SMTPAuth = true;  // authentication enabled
$mail->Username = 'webmaster@mydomain.org';
$mail->Password = 'mypassword';
$mail->SMTPSecure = 'tls'; // secure transfer enabled REQUIRED for GMail or 'tls'
$mail->Port = 25; //25 or 587

$mail->setFrom('director@mydomain.org');   //if I change .org to .com. it works.

$mail->isHTML(true);

$mail->Subject = 'Testing';
$mail->Body = 'Testing body';
$mail->addAddress('mygmailaccount@gmail.com');

if(!$mail->send()) {
	echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
	echo 'Message has been sent';
}
?>

**Comment by Synchro** [comment] 2015-11-19 14:50
The code is not in question. Please post your debug output.

**Comment by beijingnj** [comment] 2015-11-19 23:40
Here is debug output: ($mail->Body has same issue)
----------------------------------------------
2015-11-19 23:37:26	SERVER -> CLIENT: 220 ESMTP Thu, 19 Nov 2015 18:37:26 -0500: UCE strictly prohibited 2015-11-19 23:37:26	CLIENT -> SERVER: EHLO yhls.yinghuaschool.org 2015-11-19 23:37:26	SERVER -> CLIENT: 250-bosauthsmtp01.yourhostingaccount.com Hello yhls.yinghuaschool.org [66.96.183.90] 250-SIZE 34603008 250-8BITMIME 250-PIPELINING 250-AUTH PLAIN LOGIN 250-STARTTLS 250 HELP 2015-11-19 23:37:26	CLIENT -> SERVER: STARTTLS 2015-11-19 23:37:26	SERVER -> CLIENT: 220 TLS go ahead 2015-11-19 23:37:26	CLIENT -> SERVER: EHLO yhls.yinghuaschool.org 2015-11-19 23:37:26	SERVER -> CLIENT: 250-bosauthsmtp01.yourhostingaccount.com Hello yhls.yinghuaschool.org [66.96.183.90] 250-SIZE 34603008 250-8BITMIME 250-PIPELINING 250-AUTH PLAIN LOGIN 250 HELP 2015-11-19 23:37:26	CLIENT -> SERVER: AUTH LOGIN 2015-11-19 23:37:26	SERVER -> CLIENT: 334 VXNlcm5hbWU6 2015-11-19 23:37:26	CLIENT -> SERVER: d2VibWFzdGVyQHlpbmdodWFzY2hvb2wub3Jn 2015-11-19 23:37:26	SERVER -> CLIENT: 334 UGFzc3dvcmQ6 2015-11-19 23:37:26	CLIENT -> SERVER: eWluZ0h1YTE= 2015-11-19 23:37:26	SERVER -> CLIENT: 235 Authentication succeeded 2015-11-19 23:37:26	CLIENT -> SERVER: MAIL FROM: 2015-11-19 23:37:26	SERVER -> CLIENT: 250 OK 2015-11-19 23:37:26	CLIENT -> SERVER: RCPT TO: 2015-11-19 23:37:30	SERVER -> CLIENT: 250 Accepted 2015-11-19 23:37:30	CLIENT -> SERVER: DATA 2015-11-19 23:37:30	SERVER -> CLIENT: 354 Enter message, ending with "." on a line by itself 2015-11-19 23:37:30	CLIENT -> SERVER: Date: Thu, 19 Nov 2015 18:37:26 -0500 2015-11-19 23:37:30	CLIENT -> SERVER: To: beijing.nj@gmail.com 2015-11-19 23:37:30	CLIENT -> SERVER: From: director@yinghua.org 2015-11-19 23:37:30 CLIENT -> SERVER: Subject: Testing 2015-11-19 23:37:30	CLIENT -> SERVER: Message-ID: <8bd2fdc4c0e551465f9046654f60d94f@yhls.yinghuaschool.org> 2015-11-19 23:37:30	CLIENT -> SERVER: X-Mailer: PHPMailer 5.2.14 (https://github.com/PHPMailer/PHPMailer) 2015-11-19 23:37:30	CLIENT -> SERVER: MIME-Version: 1.0 2015-11-19 23:37:30	CLIENT -> SERVER: Content-Type: text/html; charset=iso-8859-1 2015-11-19 23:37:30	CLIENT -> SERVER: Content-Transfer-Encoding: 8bit 2015-11-19 23:37:30	CLIENT -> SERVER: 2015-11-19 23:37:30	CLIENT -> SERVER: Testing body 2015-11-19 23:37:30	CLIENT -> SERVER: 2015-11-19 23:37:30	CLIENT -> SERVER: . 2015-11-19 23:37:30	SERVER -> CLIENT: 250 OK id=1ZzYle-0000u1-0l 2015-11-19 23:37:30	CLIENT -> SERVER: QUIT 2015-11-19 23:37:30	SERVER -> CLIENT: 221 bosauthsmtp01.yourhostingaccount.com closing connection

**Comment by Synchro** [comment] 2015-11-20 07:10
Er, that shows an entirely successful delivery.

**Comment by beijingnj** [comment] 2015-11-20 14:14
That's the problem. I can't receive the email if I use setFrom('from@sample.org'). But I can receive the email with setFrom('from@sample.com') 
And if setFrom is using .com and the Body includes some .org letter, no can receive email neither.

**Comment by Synchro** [comment] 2015-11-20 14:21
The transcript shows a successful delivery, and PHPMailer's involvement ends there. If your mail server is having problems delivering after that, it will be in your mail server's log.

**Comment by beijingnj** [comment] 2015-11-20 14:23
Actually, Can you please try it on your web host with setFrom('from@sample.org') or Body = 'www.sample.org'? See if you can receive email. If you can, so that mean our web host server has some problem. 
Appreciate it.

**Comment by Synchro** [comment] 2015-11-20 14:28
I have no trouble sending to, from or mentioning .org domains. This is a problem with your mail server.

**Closed** 2015-12-18 17:36 UTC

**Comment by khandah** [comment] 2016-07-13 06:01
I think that, the receiver think that it is a spam or something else.
