### ISSUE TITLE
Mail Problem

### ISSUE THREAD

**Issue by Bhaskar1989** [PHPMailer/PHPMailer#715] opened 2016-05-11 14:02 UTC
Hi,

When we send mail. In inbox, proper mail not see in the inbox. And  show error of incorrect addres, but  address is correct.

Delivery to the following recipient failed permanently:

     bhaskarbisht571@gmail

Technical details of permanent failure:
DNS Error: 18395279 DNS type 'mx' lookup of gmail responded with code NOERROR
18395279 DNS type 'mx' lookup of gmail had no relevant answers.
18395279 DNS type 'aaaa' lookup of gmail responded with code NOERROR
18395279 DNS type 'aaaa' lookup of gmail had no relevant answers.
18395279 DNS type 'a' lookup of gmail responded with code NOERROR
18395279 DNS type 'a' lookup of gmail had no relevant answers

Why showing  bhaskarbisht571@gmail instead of  bhaskarbisht571@gmail.com.

**Comment by ooxi** [comment] 2016-05-11 14:48
Why did you open multiple issues? This is already resolved by #713

**Comment by Bhaskar1989** [comment] 2016-05-11 18:01
Sory but i thought that ticket #713 was closed. So we make a fresh ticket.

**Comment by Synchro** [comment] 2016-05-11 18:31
But it's for the same problem that was caused by your own mistake that I pointed out??

**Closed by Synchro** 2016-05-11 18:31 UTC
