### ISSUE TITLE
Is this a bug? line break and space in the attachment name.

### ISSUE THREAD

**Issue by Felipebros** [PHPMailer/PHPMailer#1624] opened 2018-12-20 18:02 UTC
https://github.com/PHPMailer/PHPMailer/blob/481715d711f4f363b499883205590e4df9e49fd3/src/PHPMailer.php#L3130

If you put the code below after line 3130, it resolves the attachment name problem with space greater than 77 characters in the name.

`$encoded = str_replace(PHP_EOL, '', $encoded);`
`$encoded = str_replace(' ', '', $encoded);`

**Comment by Synchro** [comment] 2018-12-21 08:02
It might solve that problem, but it does so by removing line breaks, which will result in lines that are too long, which is an RFC contravention, and stripping spaces, which will break lossless folding. This is likely to break header folding in general, particularly DKIM.

That said, that `preg_match` is odd - it seems to be a no-op, replacing each line with itself!

**Comment by Felipebros** [comment] 2018-12-21 11:03
I tried to remove the space in the file name that is my problem, it does not resolve, the file name is cut in half and with quotation marks before the file name

**Comment by babuhacker** [comment] 2019-06-23 12:28
i have a doubt.
$mail->Username   = "xxxxx@gmail.com";  // GMAIL username
$mail->Password   = "********";            // GMAIL password

it will steal my gmail username and password.
why we give gmail password.
what should i do.

**Comment by Synchro** [comment] 2019-09-24 10:55
Closing as a duplicate of #1469.

**Closed by Synchro** 2019-09-24 10:55 UTC
