### ISSUE TITLE
DKIM Problem after upgrading from 6.1.1 to 6.1.2

### ISSUE THREAD

**Issue by angerits** [PHPMailer/PHPMailer#1902] opened 2019-11-21 14:31 UTC
Encountered a very strange phenomena after upgrading to 6.1.2

Office 365 accounts would show empty bodies but intact attachments. Google has no problem. GMX shows messed up bodies. mail-tester.com complains about an invalid DKIM signature.

After downgrading back to 6.1.1 everything works like a charm again.

I'm guessing, that the "Substantial revision of DKIM header generation" is responsible.

What kind of info do you need to be able to track this down? You can check mail-tester output at https://www.mail-tester.com/test-7rxad

**Comment by angerits** [comment] 2019-11-21 14:37
Using SMTP to push to an postal server running on 1.0.0-dev

**Comment by Synchro** [comment] 2019-11-21 15:21
Duplicate of #1889

**Closed by Synchro** 2019-11-21 15:21 UTC
