### ISSUE TITLE
Call to protected method SMTP::errorHandler() from context 'PHPMailer'

### ISSUE THREAD

**Issue by mpryvkin** [PHPMailer/PHPMailer#900] opened 2016-12-16 12:58 UTC
I was supplying wrong credentials for SMTP when I got this error message.

>Call to protected method SMTP::errorHandler() from context 'PHPMailer' in /var/www/classes/PHPMailer/class.phpmailer.php on line 1677

Error occurs in [class.phpmailer.php (1677)](https://github.com/PHPMailer/PHPMailer/blob/f475467ee3720c6220aab047d0dae5213ddcec41/class.phpmailer.php#L1677), but it appears that `SMTP::errorHandler` is protected method.

Then I searched for this error and also found [this report](https://scrutinizer-ci.com/g/PHPMailer/PHPMailer/inspections/43fc46b5-886f-4538-8b25-a26a2c246997/issues/files/class.smtp.php?status=new&orderField=path&order=asc&honorSelectedPaths=0).

**Comment by Synchro** [comment] 2016-12-16 13:21
You must be using an old version. The PHPMailer class does not call an `errorHandler` function at all, and it's marked as protected in the SMTP class.

**Comment by mpryvkin** [comment] 2016-12-16 13:48
I'm using 5.2.16 and got the error mentioned below when supplied credentials were incorrect. Not sure why you're closing the issue without first trying to figure out the source of the problem.

**Comment by Synchro** [comment] 2016-12-16 13:52
The two links you provided point to things that no longer exist. Line 1677 in class.phpmailer.php does not contain a call to `SMTP::errorHandler()`, and the errorHandler method in the SMTP class *is* declared as protected, so that scrutinizer note must apply to some older version (also note that the line numbers too not match up). There are no calls to `errorHandler` *anywhere* in the PHPMailer class; the string does not exist in the file.

**Comment by Synchro** [comment] 2016-12-16 13:57
Aha - I see why - there were fixed in 5.2.17, so you need to update.

**Comment by mpryvkin** [comment] 2016-12-16 13:57
[This commit](https://github.com/PHPMailer/PHPMailer/commit/d9412709509945bcc94951bbf28f5157546a1316) added error handling by protected method `errorHandler()` to `class.smtp.php`. Not sure why this method is called in the context 'PHPMailer'.

**Comment by mpryvkin** [comment] 2016-12-16 14:00
I see [this fix](https://github.com/PHPMailer/PHPMailer/commit/7c1154b63cf729e8cb5daac5c7a3c23883dde8fb) now, it probably fixes the problem I was getting. Thanks!

**Comment by mpryvkin** [comment] 2016-12-16 14:07
I see [this commit](https://github.com/PHPMailer/PHPMailer/commit/7c1154b63cf729e8cb5daac5c7a3c23883dde8fb), however I just checked that I was using `master` branch downloaded month ago which includes above mentioned fix. Any ideas?

**Comment by Synchro** [comment] 2016-12-16 14:10
Can you reproduce it with current master (or 5.2.17)?

**Comment by mpryvkin** [comment] 2016-12-16 14:14
I'm using [this version](https://github.com/PHPMailer/PHPMailer/tree/e4233553504a3645cb77e2a821e59fd1536445e1), and one commit after that is in some other unrelated area.

**Comment by Synchro** [comment] 2016-12-16 14:28
The only thing I can think of is if `$this` is somehow not what it should be at the time. Can you please post code to reproduce and a stack trace when the error occurs, so we can see how it's getting to that point?

**Comment by mpryvkin** [comment] 2016-12-16 14:57
Code to reproduce the problem is shown below. This occurs only if I supply wrong SMTP credentials.

```
require_once("classes/PHPMailer/PHPMailerAutoload.php");
 
$mail = new PHPMailer;
 
$mail->isSMTP();
$mail->SMTPAuth   = TRUE;
$mail->XMailer    = ' ';
$mail->AllowEmpty = TRUE;
$mail->SMTPDebug  = 0;
 
$mail->Host       = 'HIDDEN';
$mail->Port       = 25;
$mail->Username   = 'HIDDEN';
$mail->Password   = 'HIDDEN';
$mail->SMTPSecure = '';
 
$mail->setFrom('sender@domain.com');
$mail->addAddress('receipient@domain.com');
 
$mail->Subject = 'This is a test subject';
$mail->Body    = 'This is a test body';
 
# Deliver the message
$success = $mail->send();
```

Function `debug_print_backtrace()` placed on line [1677](https://github.com/PHPMailer/PHPMailer/blob/f475467ee3720c6220aab047d0dae5213ddcec41/class.phpmailer.php#L1677) produces the following output:

```
#0  PHPMailer->smtpClose() called at [classes/PHPMailer/class.phpmailer.php:670]
#1  PHPMailer->__destruct()
```

**Comment by Synchro** [comment] 2017-03-07 11:55
`$mail->SMTPSecure = '';` sets an invalid value for `SMTPSecure`, though that didn't make a difference to me.

I can't reproduce this, closing.

**Closed by Synchro** 2017-03-07 11:55 UTC
