### ISSUE TITLE
Bug when sending multipart/mixed message "manually"

### ISSUE THREAD

**Issue by tsteur** [PHPMailer/PHPMailer#2134] opened 2020-09-10 20:48 UTC
Hi there,

I noticed an issue with sending multipart/mixed message through a WordPress plugin. What's happening is that we actually configure PHPMailer to send a multipart/mixed message and send already the boundary in the header and content ourselves. I have a script to reproduce this issue here: https://gist.github.com/tsteur/6f23840e49cd7f8dc349d4c5bdfed33e

What's happening is that it works nicely in gmail and most other email clients, but Outlook in Office 365 shows this:

![image](https://user-images.githubusercontent.com/273120/92802216-6afc6e80-f40a-11ea-9c95-8db341da51e9.png)

instead of this 

![image](https://user-images.githubusercontent.com/273120/92802252-751e6d00-f40a-11ea-93f4-ba047c3a95a4.png)

The problem is that it adds here https://github.com/PHPMailer/PHPMailer/blob/v6.1.7/src/PHPMailer.php#L2493 an additional content type header which is confusing office 365 and overwriting the Content Type multipart/mixed header. This is what the header looks like

```
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline
Content-Type: multipart/mixed; boundary="=_c3518fdad4b76fd9cadcb3e3cffc7698"
MIME-Version: 1.0
Content-Type: multipart/mixed; charset=UTF-8

--=_c3518fdad4b76fd9cadcb3e3cffc7698
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline
```

This is what it should look like

```
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline
Content-Type: multipart/mixed; boundary="=_c3518fdad4b76fd9cadcb3e3cffc7698"
MIME-Version: 1.0

--=_c3518fdad4b76fd9cadcb3e3cffc7698
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline
```

I suppose there are various ways to fix this issue. For example not adding that extra header if `$this->ContentType === 'multipart/mixed';` or setting the correct message type (`attach`) if any of the custom headers already contain the multipart mixed header with a boundary here https://github.com/PHPMailer/PHPMailer/blob/v6.1.7/src/PHPMailer.php#L2907 so it would simply duplicate the `Content-Type: multipart/mixed; boundary="=_c3518fdad4b76fd9cadcb3e3cffc7698"` instead of using `Content-Type: text/html; charset=utf-8`.

Let me know if this helps you or if you need any more information. You should be able to reproduce the issue with the linked PHP script. I know we could use things like `$phpMailer->addStringAttachment()` but this is not as easily possible in WordPress and we can't use the regular way to add attachments in WordPress because we have the attachments as a string and not a file and for security reasons we would not want to create a file so it can be used using `wp_mail()`.

Be great to make this use case work. Thanks

**Comment by Synchro** [comment] 2020-09-10 21:00
The problem is here:

> send already the boundary in the header and content ourselves

You're really swimming against the current here. PHPMailer builds multiparts for you, and what you're seeing is what happens when you try to subvert that.

Looking at your script, I don't see anything preventing you from using `addStringAttachment` – you already have the content in a string, and you have the phpmailer instance on hand. There isn't anything else you need. If your content is already encoded (as in your example script), just decode it first.

I don't see a compelling argument here.

**Comment by tsteur** [comment] 2020-09-10 21:13
@Synchro fully aware of this. We're using `addStringAttchment` in Matomo itself but it's not as trivial in WordPress. If you're not keen on supporting this use case let me know and we would need to figure out a different way.

**Comment by Synchro** [comment] 2020-09-10 22:02
If you build the message structure yourself, you may as well use `mail()` directly since PHPMailer isn't really doing anything for you.

If your example code is runnable in your Wordpress context, why can't you do [this](https://gist.github.com/Synchro/46185ae95e03ea83be80215ef6dfa916) instead? I tested that locally and it works very nicely, with quite a bit less complexity. Put it another way – if you can generate a message structure containing the encoded file, then you can just generate the encoded file and use that directly without the enclosing message structure.

Incidentally you have lots of inconsistencies in your HTML - sometimes `&` in URLs is (correctly) encoded as `&amp;`, but sometimes it's not. You have some curly quotes around font names (which will break), quite a few characters that are unnecessarily encoded (e.g. `&#x20;`). I'd recommend sticking it through the W3C validator to ensure you're generating valid HTML. Overall, you don't need to use a quoted-printable CTE at all; PHPMailer figures out whether and how to encode the body or not. Those sort of issues are likely to cause problems across different email clients.

**Comment by tsteur** [comment] 2020-09-14 01:57
Hi @Synchro that's what we're doing in our standalone Matomo solution and works nicely 👍 

 In our WordPress integration all we have is `wp_mail( string|array $to, string $subject, string $message, string|array $headers = '', string|array $attachments = array() )` which then uses PHPMailer. WordPress expects the attachments to be file paths. However, we have the attachment as strings and we generally prefer not to store the data on disk because the attachment data may then become accessible through the web. Especially if for some reason it fails to delete the data again.

**Comment by Synchro** [comment] 2020-09-14 08:19
If you're doing this inside a WP plugin, you can get a handle on the underlying PHPMailer instance it uses by using the [`phpmailer_init`] hook`](https://developer.wordpress.org/reference/hooks/phpmailer_init/), and you can use that to add string attachments before calling `wp_mail()`.

Alternatively, can you pass in a php memory stream containing your content (like `php://memory`) as a file path? That should work in most `fopen()` scenarios, but I've not tried it.

The main issue here is way beyond resolving a simple duplicate header; it's completely counter to the entire structure of PHPMailer, and will not be possible to fix just by juggling a few small things.

**Comment by tsteur** [comment] 2020-09-16 00:30
OK Thanks @Synchro 

I was hoping it would be a somewhat easy fix that would maybe give also a bit more flexibility. Feel free to close it as a won't fix for now and we'll see how we can workaround things. I'll give tr the `php://memory` a try see if this works nicely 👍 . Feel free to close for now.

**Comment by tsteur** [comment] 2020-09-17 02:22
In case someone else is wondering the same `php:memory` doesn't really work since we cannot define a filename for it. We're working around it using the `phpmailer_init` hook now and `addStringAttachment`

**Closed** 2020-09-30 16:51 UTC
