### ISSUE TITLE
Unable to receive emails sent to Office 365

### ISSUE THREAD

**Issue by cova-sa** [PHPMailer/PHPMailer#965] opened 2017-01-16 19:07 UTC
I created some php code to send out emails and I'm able to receive the emails on every email account with exception of Office 365. Is there a reason why I can't receive email to the 365 mail server?

I'm sending it from inmotionhosting.com

```
                  $mail = new PHPMailer();
		  $mail->SMTPDebug = 2;
		  $mail->SMTPAuth = true;
		  $mail->SMTPSecure = "tls";
		  $mail->Host = "secure##.inmotionhosting.com";
		  $mail->Port = '587';
		  $mail->Username = "username";
		  $mail->Password = "password";
		  $mail->CharSet = 'windows-1250';
		  $mail->SetFrom ('noreply@domain.com', 'Ticket Submission'); 
		  $mail->Subject = $email->subject;
		  $mail->ContentType = 'text/plain'; 
		  $mail->IsHTML(false);
		  $mail->Body = $email->body;
		  $mail->AddAddress ('stephen@domain.com', 'Stephen Adkins');
		  $mail->AddAddress ('clay.smith@domain.com', 'Clay Smith');
		  var_dump($mail->Send());
```

The username and password were provided by the host and again I'm receiving the emails on gmail, hotmail, etc. It's only on 365 that I'm not receiving any emails. Also, where do I go to see the SMTPDebug results, because I'm only getting "true" from the var_dump($mail->Send())?

**Comment by Synchro** [comment] 2017-01-16 19:11
It should be dumping output directly to your browser or console. It may not if you have some kind of output buffering enabled - test this email code in isolation. Your settings look correct, but SMTP debug output will definitely let you know what's happening. That said, given that it's saying it's sent successfully, it probably has and messages may be sitting in a spam box.

**Comment by cova-sa** [comment] 2017-01-16 19:21
There doesn't seem to be any trace of the emails in the spam folder either. Is there any way to tell if the email was successfully received by the recipient email server?

**Comment by Synchro** [comment] 2017-01-16 19:38
Yes, by showing the debug output.

**Comment by cova-sa** [comment] 2017-01-16 19:42
So I change that process and decided to try connecting to the recipients mail server using their host name, user name, and password. When I sent the email I got "Your message to noreply@domain.com couldn't be delivered. noreply wasn't found at domain.com." This was sent to me in an email and this is because I set the property $mail->SetFrom ('noreply@domain.com', 'Ticket Submission'); Also, even though I got this email, the debug still only printed out true and no errors.

**Comment by cova-sa** [comment] 2017-01-16 20:10
I'm change the code to look like this and still no luck.
		  ```
                  require_once('scripts/phpmailer/class.phpmailer.php');
		  $mail = new PHPMailer();
		  $mail->SMTPDebug = 2;
		  $mail->SMTPAuth = true;
		  $mail->SMTPSecure = "tls";
		  $mail->Host = "smtp.office365.com";
		  //$mail->Host = "domain-com.mail.protection.outlook.com";
		  $mail->Port = '587';
		  $mail->Username = "Website@domain.com";
		  $mail->Password = "password";
		  $mail->CharSet = 'windows-1250';
		  $mail->SetFrom ('website@domain.com', 'Ticket Submission'); 
		  $mail->Subject = $email->subject;
		  $mail->ContentType = 'text/plain'; 
		  $mail->IsHTML(false);
		  $mail->Body = $email->body;
		  $mail->AddAddress ('Website@domain.com', 'Clay Smith');
		  $mail->AddAddress ('Website@mailserver.domain.com', 'Clay Smith');
```

I logged into the email account Website@domain.com via the outlook.office365.com weblink and I don't see anything in the Inbox or the Junk Email list. I also am still not getting an errors from the debug option.

**Comment by Synchro** [comment] 2017-01-16 21:22
You've based your code on an obsolete example - use the ones bundled with PHPMailer, and make sure you're using the latest version.

One fundamental thing is missing: you're not telling it to send using SMTP, so none of this is going via outlook at all. Add this line and your script should get a lot noisier:

    $mail->isSMTP();

You'll need to use the autoloader, or composer, or load the SMTP class too, just as the readme says.

**Comment by cova-sa** [comment] 2017-01-16 21:47
After making those edits the problem has been solved. Thank you so much for the help. Looking forward to continuous use.

**Comment by Synchro** [comment] 2017-01-16 21:49
Glad that worked out. Could you delete the question on Stackoverflow that's a duplicate of this?

**Comment by cova-sa** [comment] 2017-01-16 21:50
Will do

**Closed by Synchro** 2017-01-16 21:49 UTC
